import { create } from "zustand";
const dataExmaple = [
  {
    idVtex_order: "1258240017082-01",
    sequence_order: 522339,
    idProscai_order: "N/A",
    invoiceKey_order: "N/A",
    ticket_order: null,
    status_order: "invoiced",
    statusDescription_order: "Faturado",
    status2_order: 7,
    value_order: 3980,
    creationDate_order: "31-08-2022 11:00:15 AM",
    creationDate2_order: "2022-08-31T11:00:15.000Z",
    totalItems_order: 5300,
    qtyItems_order: 0,
    totalDiscounts_order: -1320,
    totalShipping_order: 0,
    customerName_order: "Jesus Alejandro martinez",
    customerPhone_order: "+525612022023",
    customerEmail_order: "yakatlakatl@gmail.com",
    customerCName_order: "N/A",
    addressType_order: "pickup",
    receiverName_order: "Jesus Alejandro martinez",
    postalCode_order: 6880,
    city_order: "CUAUHTÉMOC",
    state_order: "Ciudad de México",
    country_order: "MEX",
    street_order:
      "Calle Isabel la Católica No. 487, Col. Algarín, C.P. 06880, Alcaldía Cuauhtémoc",
    number_order: "",
    neighborhood_order: "Algarin",
    courier_order: "Sucursal Isabela Catolica",
    courierId_order: "1b3990d",
    deliveryChannel_order: "pickup-in-point",
    trackingNumber_order: null,
    shippingLabel_order: null,
    warehouse_order: "",
    total_order: 3980,
    paymentSystemName_order: "KUESKI",
    paymentSystemId_order: "",
    paymentGroup_order: "promissory",
    transactionId_order: "6151C84A0D5A46D6ABC8F525E0CBA865",
    paymentId_order: "",
    paymentTid_order: "N/A",
    dateTimeInsert_order: "28-09-2022 09:46:17",
    originOperation_order: "MEX",
    manualLabel_order: false,
    picking_assigment: [1, 23],
    packing_assigment: null,
  },
  {
    idVtex_order: "1258282516086-01",
    sequence_order: 522355,
    idProscai_order: "N/A",
    invoiceKey_order: "N/A",
    ticket_order: null,
    status_order: "invoiced",
    statusDescription_order: "Faturado",
    status2_order: 7,
    value_order: 459,
    creationDate_order: "31-08-2022 02:41:55 PM",
    creationDate2_order: "2022-08-31T14:41:55.000Z",
    totalItems_order: 552,
    qtyItems_order: 0,
    totalDiscounts_order: -172,
    totalShipping_order: 79,
    customerName_order: "Jorge Yzar Muñoz",
    customerPhone_order: "+524492631529",
    customerEmail_order: "jake.yzar@gmail.com",
    customerCName_order: "N/A",
    addressType_order: "residential",
    receiverName_order: "Jorge Yzar Muñoz",
    postalCode_order: 20126,
    city_order: "AGUASCALIENTES",
    state_order: "AGUASCALIENTES",
    country_order: "MEX",
    street_order: "La estancia",
    number_order: "114",
    neighborhood_order: "Villa de Nuestra Señora de la Asunción",
    courier_order: "Paquetexpress Estándar",
    courierId_order: "mex",
    deliveryChannel_order: "delivery",
    trackingNumber_order: null,
    shippingLabel_order: null,
    warehouse_order: "027",
    total_order: 459,
    paymentSystemName_order: "PayPal",
    paymentSystemId_order: "12",
    paymentGroup_order: "payPal",
    transactionId_order: "28A4EBA7EB0542129253FC397884DA8E",
    paymentId_order: "F70EBD149EE04C2A9A9123192CAFB5E9",
    paymentTid_order: "N/A",
    dateTimeInsert_order: "30-09-2022 05:22:32",
    originOperation_order: "MEX",
    manualLabel_order: false,
    picking_assigment: [23],
    packing_assigment: [23],
  },
  {
    idVtex_order: "1258440731848-01",
    sequence_order: 522381,
    idProscai_order: "N/A",
    invoiceKey_order: "N/A",
    ticket_order: null,
    status_order: "invoiced",
    statusDescription_order: "Faturado",
    status2_order: 10,
    value_order: 1158.98,
    creationDate_order: "01-09-2022 07:12:10 AM",
    creationDate2_order: "2022-09-01T07:12:10.000Z",
    totalItems_order: 1350,
    qtyItems_order: 0,
    totalDiscounts_order: -396,
    totalShipping_order: 204.98,
    customerName_order: "Alexander  Lopez mendez ",
    customerPhone_order: "+527551406659",
    customerEmail_order: "alex14.com55@gmail.com",
    customerCName_order: "ALEXANDER LOPEZ MENDEZ ",
    addressType_order: "residential",
    receiverName_order: "Alexander lopez mendez ",
    postalCode_order: 95580,
    city_order: "JOSÉ AZUETA",
    state_order: "Veracruz",
    country_order: "MEX",
    street_order: "Alvaro obregon  ",
    number_order: "95",
    neighborhood_order: "Venecia ",
    courier_order: "Estafeta Zona Extendida",
    courierId_order: "12f15e8",
    deliveryChannel_order: "delivery",
    trackingNumber_order: null,
    shippingLabel_order: null,
    warehouse_order: "027",
    total_order: 1158.98,
    paymentSystemName_order: "Visa",
    paymentSystemId_order: "",
    paymentGroup_order: "creditCard",
    transactionId_order: "E0044E30BDD94881ACB9123B78EA104B",
    paymentId_order: "",
    paymentTid_order: "N/A",
    dateTimeInsert_order: "13-09-2022 05:54:25",
    originOperation_order: "MEX",
    manualLabel_order: false,
    picking_assigment: null,
    packing_assigment: null,
  },
  {
    idVtex_order: "1258461406494-01",
    sequence_order: 522385,
    idProscai_order: "N/A",
    invoiceKey_order: "N/A",
    ticket_order: null,
    status_order: "invoiced",
    statusDescription_order: "Faturado",
    status2_order: 10,
    value_order: 687,
    creationDate_order: "01-09-2022 09:23:26 AM",
    creationDate2_order: "2022-09-01T09:23:26.000Z",
    totalItems_order: 831,
    qtyItems_order: 0,
    totalDiscounts_order: -313,
    totalShipping_order: 169,
    customerName_order: "Martin Cortez Silva",
    customerPhone_order: "+524981043701",
    customerEmail_order: "arq_mcs@hotmail.com",
    customerCName_order: "N/A",
    addressType_order: "residential",
    receiverName_order: "Martin Cortez Silva",
    postalCode_order: 98422,
    city_order: "RÍO GRANDE",
    state_order: "ZACATECAS",
    country_order: "MEX",
    street_order: "CALLE ALDAMA",
    number_order: "67",
    neighborhood_order: "centro",
    courier_order: "Estafeta Estandar Domicilio",
    courierId_order: "Estafetav2",
    deliveryChannel_order: "delivery",
    trackingNumber_order: null,
    shippingLabel_order: null,
    warehouse_order: "027",
    total_order: 687,
    paymentSystemName_order: "Visa",
    paymentSystemId_order: "",
    paymentGroup_order: "creditCard",
    transactionId_order: "3524826A1B6349209A3415554D8240FD",
    paymentId_order: "",
    paymentTid_order: "N/A",
    dateTimeInsert_order: "13-09-2022 05:56:12",
    originOperation_order: "MEX",
    manualLabel_order: false,
    picking_assigment: null,
    packing_assigment: null,
  },
  {
    idVtex_order: "1258731621126-01",
    sequence_order: 522461,
    idProscai_order: "N/A",
    invoiceKey_order: "N/A",
    ticket_order: null,
    status_order: "invoiced",
    statusDescription_order: "Faturado",
    status2_order: 5,
    value_order: 287,
    creationDate_order: "02-09-2022 12:27:01 PM",
    creationDate2_order: "2022-09-02T12:27:01.000Z",
    totalItems_order: 464,
    qtyItems_order: 0,
    totalDiscounts_order: -256,
    totalShipping_order: 79,
    customerName_order: "Monica Irina González Becerra ",
    customerPhone_order: "+523931090735",
    customerEmail_order: "irina_8905@hotmail.com",
    customerCName_order: "N/A",
    addressType_order: "residential",
    receiverName_order: "Monica Irina González Becerra ",
    postalCode_order: 47913,
    city_order: "LA BARCA",
    state_order: "Jalisco",
    country_order: "MEX",
    street_order: "Rio de los Sabinos",
    number_order: "50",
    neighborhood_order: "Loma Bonita",
    courier_order: "Paquetexpress Estándar",
    courierId_order: "mex",
    deliveryChannel_order: "delivery",
    trackingNumber_order: null,
    shippingLabel_order: null,
    warehouse_order: "027",
    total_order: 287,
    paymentSystemName_order: "Transferencia BBVA",
    paymentSystemId_order: "",
    paymentGroup_order: "promissory",
    transactionId_order: "E61871DEFB6440B39B532A7404427214",
    paymentId_order: "",
    paymentTid_order: "N/A",
    dateTimeInsert_order: "13-09-2022 05:55:52",
    originOperation_order: "MEX",
    manualLabel_order: false,
    picking_assigment: null,
    packing_assigment: [23],
  },
  {
    idVtex_order: "1259802959519-01",
    sequence_order: 522723,
    idProscai_order: "N/A",
    invoiceKey_order: "N/A",
    ticket_order: null,
    status_order: "invoiced",
    statusDescription_order: "Faturado",
    status2_order: 10,
    value_order: 613.5,
    creationDate_order: "06-09-2022 10:49:19 PM",
    creationDate2_order: "2022-09-06T22:49:19.000Z",
    totalItems_order: 486,
    qtyItems_order: 0,
    totalDiscounts_order: -91.5,
    totalShipping_order: 219,
    customerName_order: "Hector Ardinez escoto ",
    customerPhone_order: "+522281429757",
    customerEmail_order: "hectorardinez@icloud.com",
    customerCName_order: "N/A",
    addressType_order: "residential",
    receiverName_order: "Hector Ardinez escoto ",
    postalCode_order: 91687,
    city_order: "LA ANTIGUA",
    state_order: "Veracruz",
    country_order: "MEX",
    street_order: "Venustiano Carranza s/n esquina Rodríguez cano",
    number_order: "S/n",
    neighborhood_order: "Centro ",
    courier_order: "Estafeta Express",
    courierId_order: "estafeta-express",
    deliveryChannel_order: "delivery",
    trackingNumber_order: null,
    shippingLabel_order: null,
    warehouse_order: "027",
    total_order: 613.5,
    paymentSystemName_order: "PayPal",
    paymentSystemId_order: "",
    paymentGroup_order: "payPal",
    transactionId_order: "A5578FF448DC4A63B99869EBA6B2A1B5",
    paymentId_order: "",
    paymentTid_order: "N/A",
    dateTimeInsert_order: "13-09-2022 05:56:10",
    originOperation_order: "MEX",
    manualLabel_order: false,
    picking_assigment: null,
    packing_assigment: null,
  },
  {
    idVtex_order: "1259971395697-01",
    sequence_order: 522765,
    idProscai_order: "N/A",
    invoiceKey_order: "N/A",
    ticket_order: null,
    status_order: "invoiced",
    statusDescription_order: "Faturado",
    status2_order: 10,
    value_order: 667,
    creationDate_order: "07-09-2022 04:23:14 PM",
    creationDate2_order: "2022-09-07T16:23:14.000Z",
    totalItems_order: 648,
    qtyItems_order: 0,
    totalDiscounts_order: -60,
    totalShipping_order: 79,
    customerName_order: "Marlon Juárez",
    customerPhone_order: "+528127561270",
    customerEmail_order: "macalefa07@gmail.com",
    customerCName_order: "N/A",
    addressType_order: "residential",
    receiverName_order: "Marlon Juárez",
    postalCode_order: 66360,
    city_order: "SANTA CATARINA",
    state_order: "NUEVO LEÓN",
    country_order: "MEX",
    street_order: "Geranio",
    number_order: "141",
    neighborhood_order: "Misión de santa catarina",
    courier_order: "Paquetexpress Estándar",
    courierId_order: "mex",
    deliveryChannel_order: "delivery",
    trackingNumber_order: null,
    shippingLabel_order: null,
    warehouse_order: "027",
    total_order: 667,
    paymentSystemName_order: "Visa",
    paymentSystemId_order: "",
    paymentGroup_order: "creditCard",
    transactionId_order: "0336DA57267C41168EDC3E8586C476C5",
    paymentId_order: "",
    paymentTid_order: "N/A",
    dateTimeInsert_order: "13-09-2022 05:56:34",
    originOperation_order: "MEX",
    manualLabel_order: false,
    picking_assigment: null,
    packing_assigment: null,
  },
  {
    idVtex_order: "1260923274969-01",
    sequence_order: 522989,
    idProscai_order: "N/A",
    invoiceKey_order: "N/A",
    ticket_order: null,
    status_order: "invoiced",
    statusDescription_order: "Faturado",
    status2_order: 10,
    value_order: 1673.5,
    creationDate_order: "11-09-2022 02:54:33 PM",
    creationDate2_order: "2022-09-11T14:54:33.000Z",
    totalItems_order: 2238,
    qtyItems_order: 0,
    totalDiscounts_order: -564.5,
    totalShipping_order: 0,
    customerName_order: "Karina Bailey",
    customerPhone_order: "+528112304620",
    customerEmail_order: "bkebrand@gmail.com",
    customerCName_order: "N/A",
    addressType_order: "residential",
    receiverName_order: "Karina Bailey",
    postalCode_order: 66550,
    city_order: "CARMEN",
    state_order: "Nuevo León",
    country_order: "MEX",
    street_order: "Alvaro obregon",
    number_order: "506",
    neighborhood_order: "Popular",
    courier_order: "Redpack Estándar Domicilio",
    courierId_order: "1949fdf",
    deliveryChannel_order: "delivery",
    trackingNumber_order: null,
    shippingLabel_order: null,
    warehouse_order: "027",
    total_order: 1673.5,
    paymentSystemName_order: "PayPalPlus",
    paymentSystemId_order: "49",
    paymentGroup_order: "PayPalPlus",
    transactionId_order: "A2B2D5FB3C7443F4B317E4BBB81534EE",
    paymentId_order: "159B46BA252C43EBB07FF98301103506",
    paymentTid_order: "N/A",
    dateTimeInsert_order: "03-10-2022 09:39:02",
    originOperation_order: "MEX",
    manualLabel_order: false,
    picking_assigment: null,
    packing_assigment: null,
  },
  {
    idVtex_order: "1261011558818-01",
    sequence_order: 523007,
    idProscai_order: "N/A",
    invoiceKey_order: "N/A",
    ticket_order: null,
    status_order: "invoiced",
    statusDescription_order: "Faturado",
    status2_order: 10,
    value_order: 269.5,
    creationDate_order: "12-09-2022 12:25:57 AM",
    creationDate2_order: "2022-09-12T00:25:57.000Z",
    totalItems_order: 403,
    qtyItems_order: 0,
    totalDiscounts_order: -133.5,
    totalShipping_order: 0,
    customerName_order: "Maribel Lugo Huitrón ",
    customerPhone_order: "+525513949434",
    customerEmail_order: "lugohmari@gmail.com",
    customerCName_order: "N/A",
    addressType_order: "pickup",
    receiverName_order: "Maribel Lugo Huitrón ",
    postalCode_order: 6000,
    city_order: "Ciudad de México",
    state_order: "Ciudad de México",
    country_order: "MEX",
    street_order: "Calle del Correo Mayor",
    number_order: "76",
    neighborhood_order: "Centro Histórico de la Ciudad de México",
    courier_order: "Sucursal Correo Mayor",
    courierId_order: "1b51fd7",
    deliveryChannel_order: "pickup-in-point",
    trackingNumber_order: null,
    shippingLabel_order: null,
    warehouse_order: "",
    total_order: 269.5,
    paymentSystemName_order: "Visa",
    paymentSystemId_order: "",
    paymentGroup_order: "creditCard",
    transactionId_order: "60D625D9B5BC40549DBD1F30008746F0",
    paymentId_order: "",
    paymentTid_order: "N/A",
    dateTimeInsert_order: "13-09-2022 05:57:00",
    originOperation_order: "MEX",
    manualLabel_order: false,
    picking_assigment: null,
    packing_assigment: null,
  },
  {
    idVtex_order: "1261122983902-01",
    sequence_order: 523019,
    idProscai_order: "N/A",
    invoiceKey_order: "N/A",
    ticket_order: null,
    status_order: "invoiced",
    statusDescription_order: "Faturado",
    status2_order: 10,
    value_order: 950,
    creationDate_order: "12-09-2022 10:49:42 AM",
    creationDate2_order: "2022-09-12T10:49:42.000Z",
    totalItems_order: 1380,
    qtyItems_order: 0,
    totalDiscounts_order: -430,
    totalShipping_order: 0,
    customerName_order: "Fernando López Sánchez",
    customerPhone_order: "+524731374501",
    customerEmail_order: "fernandolopezsanchez6@gmail.com",
    customerCName_order: "N/A",
    addressType_order: "residential",
    receiverName_order: "Fernando López Sánchez",
    postalCode_order: 36000,
    city_order: "GUANAJUATO",
    state_order: "GUANAJUATO",
    country_order: "MEX",
    street_order: "Cerrada de mexiamora 23",
    number_order: "23",
    neighborhood_order: "Guanajuato Centro",
    courier_order: "Redpack Estándar Domicilio",
    courierId_order: "1949fdf",
    deliveryChannel_order: "delivery",
    trackingNumber_order: null,
    shippingLabel_order: null,
    warehouse_order: "027",
    total_order: 950,
    paymentSystemName_order: "Transferencia BBVA",
    paymentSystemId_order: "",
    paymentGroup_order: "promissory",
    transactionId_order: "3555ADC7E3A14B809F6862359584A85A",
    paymentId_order: "",
    paymentTid_order: "N/A",
    dateTimeInsert_order: "13-09-2022 05:18:36",
    originOperation_order: "MEX",
    manualLabel_order: false,
    picking_assigment: null,
    packing_assigment: null,
  },
  {
    idVtex_order: "1261130170958-01",
    sequence_order: 523021,
    idProscai_order: "N/A",
    invoiceKey_order: "N/A",
    ticket_order: null,
    status_order: "invoiced",
    statusDescription_order: "Faturado",
    status2_order: 10,
    value_order: 1710,
    creationDate_order: "12-09-2022 12:02:49 PM",
    creationDate2_order: "2022-09-12T12:02:49.000Z",
    totalItems_order: 2484,
    qtyItems_order: 0,
    totalDiscounts_order: -774,
    totalShipping_order: 0,
    customerName_order: "sarai cahuich yam",
    customerPhone_order: "+529821031873",
    customerEmail_order: "sarycahuich@gmail.com",
    customerCName_order: "N/A",
    addressType_order: "residential",
    receiverName_order: "sarai cahuich yam",
    postalCode_order: 24350,
    city_order: "ESCÁRCEGA",
    state_order: "Campeche",
    country_order: "MEX",
    street_order: "avenida hector perez martinez entre 55 y 53",
    number_order: "sn",
    neighborhood_order: "Unidad Esfuerzo y Trabajo II",
    courier_order: "Redpack Estándar Domicilio",
    courierId_order: "1949fdf",
    deliveryChannel_order: "delivery",
    trackingNumber_order: null,
    shippingLabel_order: null,
    warehouse_order: "027",
    total_order: 1710,
    paymentSystemName_order: "Transferencia BBVA",
    paymentSystemId_order: "",
    paymentGroup_order: "promissory",
    transactionId_order: "D97CA263E58548B68A5AFD6A82CCE080",
    paymentId_order: "",
    paymentTid_order: "N/A",
    dateTimeInsert_order: "13-09-2022 05:17:26",
    originOperation_order: "MEX",
    manualLabel_order: false,
    picking_assigment: null,
    packing_assigment: null,
  },
  {
    idVtex_order: "1261170090910-01",
    sequence_order: 523029,
    idProscai_order: "N/A",
    invoiceKey_order: "N/A",
    ticket_order: null,
    status_order: "invoiced",
    statusDescription_order: "Carência para Cancelamento",
    status2_order: 10,
    value_order: 3180,
    creationDate_order: "12-09-2022 04:01:30 PM",
    creationDate2_order: "2022-09-12T16:01:30.000Z",
    totalItems_order: 4500,
    qtyItems_order: 0,
    totalDiscounts_order: -1320,
    totalShipping_order: 0,
    customerName_order: "MARICELA GUTIERREZ PEREZ",
    customerPhone_order: "+524626536877",
    customerEmail_order: "maye_1523@hotmail.com",
    customerCName_order: "N/A",
    addressType_order: "residential",
    receiverName_order: "ELIZABETH MURILLO OCEJO",
    postalCode_order: 36690,
    city_order: "IRAPUATO",
    state_order: "GUANAJUATO",
    country_order: "MEX",
    street_order: "AVENIDA GUERRERO",
    number_order: "763",
    neighborhood_order: "ZONA CENTRO",
    courier_order: "Redpack Estándar Domicilio",
    courierId_order: "1949fdf",
    deliveryChannel_order: "delivery",
    trackingNumber_order: null,
    shippingLabel_order: null,
    warehouse_order: "027",
    total_order: 3180,
    paymentSystemName_order: "Transferencia BBVA",
    paymentSystemId_order: "",
    paymentGroup_order: "promissory",
    transactionId_order: "AD517BFB828047B99EF86BE5D959D05F",
    paymentId_order: "",
    paymentTid_order: "N/A",
    dateTimeInsert_order: "13-09-2022 04:25:03",
    originOperation_order: "MEX",
    manualLabel_order: false,
    picking_assigment: null,
    packing_assigment: null,
  },
  {
    idVtex_order: "1261182056118-01",
    sequence_order: 523033,
    idProscai_order: "N/A",
    invoiceKey_order: "N/A",
    ticket_order: null,
    status_order: "invoiced",
    statusDescription_order: "Faturado",
    status2_order: 10,
    value_order: 697,
    creationDate_order: "12-09-2022 04:34:15 PM",
    creationDate2_order: "2022-09-12T16:34:15.000Z",
    totalItems_order: 1104,
    qtyItems_order: 0,
    totalDiscounts_order: -407,
    totalShipping_order: 0,
    customerName_order: "Diana Medina",
    customerPhone_order: "+524778775831",
    customerEmail_order: "owo.apparel.mx@gmail.com",
    customerCName_order: "N/A",
    addressType_order: "pickup",
    receiverName_order: "Diana Medina",
    postalCode_order: 37480,
    city_order: "LEÓN",
    state_order: "Guanajuato",
    country_order: "MEX",
    street_order:
      "Plaza Comercial San Rafael Blvd. Juan José Torres Landa No. 1007, Local 17, C.P. 37480, León, Guanajuato",
    number_order: "",
    neighborhood_order: "Puerta San Rafael",
    courier_order: "Sucursal León",
    courierId_order: "Sucursal Leon",
    deliveryChannel_order: "pickup-in-point",
    trackingNumber_order: null,
    shippingLabel_order: null,
    warehouse_order: "",
    total_order: 697,
    paymentSystemName_order: "PayPal",
    paymentSystemId_order: "",
    paymentGroup_order: "payPal",
    transactionId_order: "4197FCA4AF86457D832C67A2686C047D",
    paymentId_order: "",
    paymentTid_order: "N/A",
    dateTimeInsert_order: "13-09-2022 05:57:30",
    originOperation_order: "MEX",
    manualLabel_order: false,
    picking_assigment: null,
    packing_assigment: null,
  },
  {
    idVtex_order: "1261222247354-01",
    sequence_order: 523037,
    idProscai_order: "N/A",
    invoiceKey_order: "N/A",
    ticket_order: null,
    status_order: "invoiced",
    statusDescription_order: "Faturado",
    status2_order: 10,
    value_order: 150,
    creationDate_order: "12-09-2022 08:37:27 PM",
    creationDate2_order: "2022-09-12T20:37:27.000Z",
    totalItems_order: 150,
    qtyItems_order: 0,
    totalDiscounts_order: 0,
    totalShipping_order: 0,
    customerName_order: "Nayeli  Martinez",
    customerPhone_order: "+523316040496",
    customerEmail_order: "naye.martinezg@gmail.com",
    customerCName_order: "N/A",
    addressType_order: "pickup",
    receiverName_order: "Nayeli  Martinez",
    postalCode_order: 44360,
    city_order: "Guadalajara",
    state_order: "Jalisco",
    country_order: "MEX",
    street_order: "Calle Juan Díaz Covarrubias",
    number_order: "74",
    neighborhood_order: null,
    courier_order: "Sucursal Guadalajara",
    courierId_order: "Sucursal Guadalajara",
    deliveryChannel_order: "pickup-in-point",
    trackingNumber_order: null,
    shippingLabel_order: null,
    warehouse_order: "",
    total_order: 150,
    paymentSystemName_order: "Visa",
    paymentSystemId_order: "",
    paymentGroup_order: "creditCard",
    transactionId_order: "3C865B8FAA144D5C878CBD394F1B686D",
    paymentId_order: "",
    paymentTid_order: "N/A",
    dateTimeInsert_order: "13-09-2022 05:57:57",
    originOperation_order: "MEX",
    manualLabel_order: false,
    picking_assigment: null,
    packing_assigment: null,
  },
  {
    idVtex_order: "1261233115093-01",
    sequence_order: 523039,
    idProscai_order: "N/A",
    invoiceKey_order: "N/A",
    ticket_order: null,
    status_order: "invoiced",
    statusDescription_order: "Faturado",
    status2_order: 10,
    value_order: 271,
    creationDate_order: "12-09-2022 09:51:53 PM",
    creationDate2_order: "2022-09-12T21:51:53.000Z",
    totalItems_order: 414,
    qtyItems_order: 0,
    totalDiscounts_order: -143,
    totalShipping_order: 0,
    customerName_order: "Verónica  Valdés García ",
    customerPhone_order: "+525517542223",
    customerEmail_order: "veronica.valdes444@gmail.com",
    customerCName_order: "N/A",
    addressType_order: "pickup",
    receiverName_order: "Verónica  Valdés García ",
    postalCode_order: 6880,
    city_order: "CUAUHTÉMOC",
    state_order: "Ciudad de México",
    country_order: "MEX",
    street_order:
      "Calle Isabel la Católica No. 487, Col. Algarín, C.P. 06880, Alcaldía Cuauhtémoc",
    number_order: "",
    neighborhood_order: "Algarin",
    courier_order: "Sucursal Isabela Catolica",
    courierId_order: "1b3990d",
    deliveryChannel_order: "pickup-in-point",
    trackingNumber_order: null,
    shippingLabel_order: null,
    warehouse_order: "",
    total_order: 271,
    paymentSystemName_order: "Visa",
    paymentSystemId_order: "",
    paymentGroup_order: "creditCard",
    transactionId_order: "7104686D9015480CA57EC9FBDA3B09BC",
    paymentId_order: "",
    paymentTid_order: "N/A",
    dateTimeInsert_order: "13-09-2022 05:58:13",
    originOperation_order: "MEX",
    manualLabel_order: false,
    picking_assigment: null,
    packing_assigment: null,
  },
  {
    idVtex_order: "1261341202225-01",
    sequence_order: 523047,
    idProscai_order: "N/A",
    invoiceKey_order: "N/A",
    ticket_order: null,
    status_order: "invoiced",
    statusDescription_order: "Faturado",
    status2_order: 10,
    value_order: 1114.5,
    creationDate_order: "13-09-2022 09:20:00 AM",
    creationDate2_order: "2022-09-13T09:20:00.000Z",
    totalItems_order: 1311,
    qtyItems_order: 0,
    totalDiscounts_order: -415.5,
    totalShipping_order: 219,
    customerName_order: "Rodrigo Nolasco",
    customerPhone_order: "+524481214122",
    customerEmail_order: "jrana0367@gmail.com",
    customerCName_order: "N/A",
    addressType_order: "residential",
    receiverName_order: "Rodrigo Nolasco",
    postalCode_order: 76850,
    city_order: "AMEALCO DE BONFIL",
    state_order: "QUERÉTARO",
    country_order: "MEX",
    street_order: "Venustiano carranza",
    number_order: "#95 Local #2",
    neighborhood_order: "Amealco de Bonfil Centro",
    courier_order: "Estafeta Express",
    courierId_order: "estafeta-express",
    deliveryChannel_order: "delivery",
    trackingNumber_order: null,
    shippingLabel_order: null,
    warehouse_order: "027",
    total_order: 1114.5,
    paymentSystemName_order: "Transferencia BBVA",
    paymentSystemId_order: "",
    paymentGroup_order: "promissory",
    transactionId_order: "154344151A394056BD1A339A0CB1F151",
    paymentId_order: "",
    paymentTid_order: "N/A",
    dateTimeInsert_order: "14-09-2022 01:00:49",
    originOperation_order: "MEX",
    manualLabel_order: false,
    picking_assigment: null,
    packing_assigment: null,
  },
  {
    idVtex_order: "1261360009398-01",
    sequence_order: 523053,
    idProscai_order: "N/A",
    invoiceKey_order: "N/A",
    ticket_order: null,
    status_order: "invoiced",
    statusDescription_order: "Faturado",
    status2_order: 10,
    value_order: 364,
    creationDate_order: "13-09-2022 11:00:07 AM",
    creationDate2_order: "2022-09-13T11:00:07.000Z",
    totalItems_order: 414,
    qtyItems_order: 0,
    totalDiscounts_order: -129,
    totalShipping_order: 79,
    customerName_order: "Nelida Maria Villarreal Castilla",
    customerPhone_order: "+528442778443",
    customerEmail_order: "andrea@promocionalesapi.com",
    customerCName_order: "N/A",
    addressType_order: "residential",
    receiverName_order: "Nelida Villarreal castilla",
    postalCode_order: 25280,
    city_order: "SALTILLO",
    state_order: "COAHUILA DE ZARAGOZA",
    country_order: "MEX",
    street_order: "campeche",
    number_order: "344",
    neighborhood_order: "republica oriente",
    courier_order: "Paquetexpress Estándar",
    courierId_order: "mex",
    deliveryChannel_order: "delivery",
    trackingNumber_order: null,
    shippingLabel_order: null,
    warehouse_order: "027",
    total_order: 364,
    paymentSystemName_order: "PayPal",
    paymentSystemId_order: "",
    paymentGroup_order: "payPal",
    transactionId_order: "69FCBD4262A742C69231814DDFA38734",
    paymentId_order: "",
    paymentTid_order: "N/A",
    dateTimeInsert_order: "14-09-2022 01:01:56",
    originOperation_order: "MEX",
    manualLabel_order: false,
    picking_assigment: null,
    packing_assigment: null,
  },
  {
    idVtex_order: "1261363143477-01",
    sequence_order: 523049,
    idProscai_order: "N/A",
    invoiceKey_order: "N/A",
    ticket_order: null,
    status_order: "invoiced",
    statusDescription_order: "Faturado",
    status2_order: 10,
    value_order: 951,
    creationDate_order: "13-09-2022 10:52:23 AM",
    creationDate2_order: "2022-09-13T10:52:23.000Z",
    totalItems_order: 1129,
    qtyItems_order: 0,
    totalDiscounts_order: -257,
    totalShipping_order: 79,
    customerName_order: "ricardo  martinez ",
    customerPhone_order: "+525577805714",
    customerEmail_order: "rickydollan@gmail.com",
    customerCName_order: "Loana Juarez Santoyo",
    addressType_order: "residential",
    receiverName_order: "Ricardo Martìnez",
    postalCode_order: 14200,
    city_order: "TLALPAN",
    state_order: "Ciudad de México",
    country_order: "MEX",
    street_order: "Sacalum",
    number_order: "365",
    neighborhood_order: "Hèroes de Padierna",
    courier_order: "Paquetexpress Estándar",
    courierId_order: "mex",
    deliveryChannel_order: "delivery",
    trackingNumber_order: null,
    shippingLabel_order: null,
    warehouse_order: "027",
    total_order: 951,
    paymentSystemName_order: "Visa",
    paymentSystemId_order: "",
    paymentGroup_order: "creditCard",
    transactionId_order: "150D7FA13BE949718E29BF6A59137105",
    paymentId_order: "",
    paymentTid_order: "N/A",
    dateTimeInsert_order: "14-09-2022 01:00:41",
    originOperation_order: "MEX",
    manualLabel_order: false,
    picking_assigment: null,
    packing_assigment: null,
  },
  {
    idVtex_order: "1261370784032-01",
    sequence_order: 523055,
    idProscai_order: "N/A",
    invoiceKey_order: "N/A",
    ticket_order: null,
    status_order: "invoiced",
    statusDescription_order: "Faturado",
    status2_order: 10,
    value_order: 2907.5,
    creationDate_order: "13-09-2022 12:13:03 PM",
    creationDate2_order: "2022-09-13T12:13:03.000Z",
    totalItems_order: 2997,
    qtyItems_order: 0,
    totalDiscounts_order: -308.5,
    totalShipping_order: 219,
    customerName_order: "Dora Cecilia Núñez Gongora ",
    customerPhone_order: "+529817500600",
    customerEmail_order: "cexy7474@gmail.com",
    customerCName_order: "N/A",
    addressType_order: "residential",
    receiverName_order: "Dora Cecilia Núñez Gongora ",
    postalCode_order: 24095,
    city_order: "CAMPECHE",
    state_order: "Campeche",
    country_order: "MEX",
    street_order:
      "Av Lopez Portillo S/N edificio de Periciales de la fiscalía general del estado de Campeche por la pluma",
    number_order: "S/N",
    neighborhood_order: "Sascalum",
    courier_order: "Estafeta Express",
    courierId_order: "estafeta-express",
    deliveryChannel_order: "delivery",
    trackingNumber_order: null,
    shippingLabel_order: null,
    warehouse_order: "027",
    total_order: 2907.5,
    paymentSystemName_order: "Mastercard",
    paymentSystemId_order: "",
    paymentGroup_order: "creditCard",
    transactionId_order: "63E2181C337941088195D08CBA050274",
    paymentId_order: "",
    paymentTid_order: "N/A",
    dateTimeInsert_order: "14-09-2022 01:02:01",
    originOperation_order: "MEX",
    manualLabel_order: false,
    picking_assigment: null,
    packing_assigment: null,
  },
  {
    idVtex_order: "1261380228345-01",
    sequence_order: 523057,
    idProscai_order: "N/A",
    invoiceKey_order: "N/A",
    ticket_order: null,
    status_order: "invoiced",
    statusDescription_order: "Faturado",
    status2_order: 10,
    value_order: 2065.5,
    creationDate_order: "13-09-2022 01:03:46 PM",
    creationDate2_order: "2022-09-13T13:03:46.000Z",
    totalItems_order: 2661,
    qtyItems_order: 0,
    totalDiscounts_order: -674.5,
    totalShipping_order: 79,
    customerName_order: "José Jesús Segura",
    customerPhone_order: "+525524717034",
    customerEmail_order: "josejesus.segurayala@gmail.com",
    customerCName_order: "N/A",
    addressType_order: "residential",
    receiverName_order: "José Jesús Segura",
    postalCode_order: 54720,
    city_order: "CUAUTITLÁN IZCALLI",
    state_order: "México",
    country_order: "MEX",
    street_order: "Avenida Iztaccíhuatl",
    number_order: "147H",
    neighborhood_order: "CTM NR1 Núcleos",
    courier_order: "Paquetexpress Estándar",
    courierId_order: "mex",
    deliveryChannel_order: "delivery",
    trackingNumber_order: null,
    shippingLabel_order: null,
    warehouse_order: "027",
    total_order: 2065.5,
    paymentSystemName_order: "Mastercard",
    paymentSystemId_order: "",
    paymentGroup_order: "creditCard",
    transactionId_order: "4EBB91D5A24E45118E47BBA6999CF9B9",
    paymentId_order: "",
    paymentTid_order: "N/A",
    dateTimeInsert_order: "14-09-2022 01:02:51",
    originOperation_order: "MEX",
    manualLabel_order: false,
    picking_assigment: null,
    packing_assigment: null,
  },
];
const useStore = create((set) => {
  console.log("contexts");
  return {
    globalData: dataExmaple,
    setGlobalData: (data) => set({ globalData: data }),
    currentData: dataExmaple,
    setCurrentData: (data) => set({ currentData: data }),
    selectedRows: [],
    setSelectedRows: (data) => set({ selectedOrders: data }),
    // toggle
    // items list for handle worksheet's products/items picking
  };
});

export default useStore;
